### ISSUE TITLE
Breaking change from 1.7.1 to 1.7.2

### ISSUE THREAD

**Issue by elincoln** [apptentive/apptentive-android#102]
Removing 'setParsePushCallback' here: https://github.com/apptentive/apptentive-android/commit/53b9bcbac721364dfc3dfaf548159d60ba3a4b9a#diff-47fd56d091a21a2279dd0df9e88b3e41L471 
...is a breaking change.  Why not use `@Deprecated` until a major point release?

**Comment by skykelsey** [comment]
Hello Elincoln,

I'm very sorry that this is causing you problems. The problem is that the new Parse SDKs do not work properly anymore, and we felt it would be better to make this change now, since the changes necessary to get this working in the latest version are pretty simple. That said, the 1.7.1 version of our SDK contains the exact same bug fixes and features as 1.7.2 minus the push notification changes.

Thanks,
Sky

**Comment by elincoln** [comment]
Which Parse SDKs did it 1.7.1 work against, 1.8.x?
Is 1.7.2 for the 1.9.x Parse SDKs?

**Comment by skykelsey** [comment]
Yes, Parse 1.8.3, sorry for the confusion.
