### ISSUE TITLE
Apptentive Internet Connection Issue?

### ISSUE THREAD

**Issue by asmenter15** [apptentive/apptentive-android#107]
Upgraded to Android sdk v2.0.1 today. For some reason when I get to the Message Center I am getting the message "Please connect to the internet to send feedback", even though I clearly have internet access. I am using..

compileSdkVersion 23
buildToolsVersion '23.0.1'
minSdkVersion 16
targetSdkVersion 23

**Comment by skykelsey** [comment]
Thanks Aaron,
This was a temporary issue affecting our server, and has been resolved.
Sky

**Comment by j-mateo** [comment]
I'm having the same issue:

compileSdkVersion 22
buildToolsVersion 22.0.1
minSdkVersion 14
targetSdkVersion 22

Apptentive sdk v2.0.1

(upgrading to buildtools 23.0.1 isn't an option at the moment)

Any ideas?

**Comment by serenskye** [comment]
I am having the same issue as well.

compileSdkVersion 23
buildToolsVersion 23.0.1
minSdkVersion 14
targetSdkVersion 23
Apptentive 2.0.1 (AAR)

**Comment by bromeostasis** [comment]
Has anyone figured this out? Having the same issue...

**Comment by skykelsey** [comment]
Hello,

Are you seeing this error screen for an extended period after you launch the app? In order to allow customization of Message Center, we download configuration from our server before allowing Message Center to be displayed. Sometimes, if you launch the app for the first time and immediately open Message Center, we haven't had a chance to fetch configuration yet. While this can be annoying during development, it's very unlikely that an end-user will launch your app for the first time and immediately try to open Message Center.

Please let me know if you are launching the app, it's online, and after more than about 15 seconds, opening Message Center still displays this error page. It would most likely be due to temporary high server load, but if it's an SDK issue we will look into it.

Thanks!
Sky

**Comment by bromeostasis** [comment]
@skykelsey I've tried this even after waiting for the app to launch, I don't think that's the issue.

Some initial hunches:

- I thought it was because I hadn't "initialized" the message center, but I went into our app's console, set up a message center, saved, and rebuilt and I'm still seeing this.
- I see `Apptentive.pause()` being called every time I tap the button to open the message center, which personally seems counter-intuitive. I set up the pause action as defined [in integration](https://docs.apptentive.com/cordova/integration/#required-integration)

Let me know if you need any more details!

**Comment by bromeostasis** [comment]
@skykelsey 

Okay, so we recently upgraded to apptentive version 2, and we were previously using the project id to determine our project. I re-read the integration guide and noticed it mentioned to use the api key in settings to denote the project. I made this switch and am good to go.

For future reference, when adding the plugin, **do not** use the id in the url of your project:

`https://be.apptentive.com/apps/**12312312312312**`

**Do** use the key in settings -> api key.

![image](https://cloud.githubusercontent.com/assets/3764641/14175038/755dab96-f716-11e5-8c27-e844c8f1c240.png)
