### ISSUE TITLE
error inflating FloatingActionButton after updating support library to 24.2.0

### ISSUE THREAD

**Issue by chris-hsu** [apptentive/apptentive-android#127]
E/UncaughtException(7190): android.view.InflateException: Binary XML file line #23: Error inflating class android.support.design.widget.FloatingActionButton
E/UncaughtException(7190): 	at android.view.LayoutInflater.createView(LayoutInflater.java:613)
E/UncaughtException(7190): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
E/UncaughtException(7190): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
E/UncaughtException(7190): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
E/UncaughtException(7190): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
E/UncaughtException(7190): 	at com.apptentive.android.sdk.module.engagement.interaction.fragment.MessageCenterFragment.onCreateView(MessageCenterFragment.java:219)

apptentive sdk version: 3.2.1
project compileSdkVersion 24
project minSdkVersion 14
project targetSdkVersion 22

**Comment by febimfelix** [comment]
Same issue. Any udate on this?

**Comment by skykelsey** [comment]
Thanks for reporting this. I'm unable to reproduce this issue. Can you please share more specific information about devices and OS versions where you saw this happen? Logs may also help, if you don't mind sending the to sky@apptentive.com

**Comment by skykelsey** [comment]
I was finally able to reproduce this by using the newest version of the Appcompat-v7 library, but without upgrading the other libraries that Apptentive depends on.

`compile 'com.android.support:appcompat-v7:24.2.1'`

The fix was to make sure that if you use a newer version of one, you use a newer version of the others as well.

```
compile 'com.android.support:appcompat-v7:24.2.1'
compile 'com.android.support:design:24.2.1'
compile 'com.android.support:cardview:24.2.1'
```

This wasn't documented, so I will update our docs to point this out. Sorry for he inconvenience, and let me know if this doesn't fix your problem.
