### ISSUE TITLE
Alert on google console for one of my app

### ISSUE THREAD

**Issue by Grasshooper** [apptentive/apptentive-android#213]
Dears,

Background: we are using appetitive-cordova plugin in one of our mobile app.
https://github.com/apptentive/apptentive-cordova/#v5.0.0

recently we got an alert from google console saying : Your app is using a  content provider with unsafe implementation of openFile.

com.apptentive.android.sdk.debug.ApptentiveAttachmentFileProvider

Can you please let me know if is this something that can be fixed by you folks or is there any workaround to rectify this issue .

please let me know if you need more details.

BR,
Gautam

**Comment by CaseyApptentive** [comment]
Hi @Grasshooper ,

Thanks for reaching out. This is the first we've heard of this issue for some time. Here are some next steps to help:

1) Could you try using the latest Cordova SDK, v5.5.2: https://github.com/apptentive/apptentive-cordova/releases

2) If you're still having problems, could you share the full error details?

3) Can you let me know which app you're working on? I want to be sure we're coordinating with your Customer Success Manager so that they can help get through any rough patches. If you'd rather not post that here, can you send the name of the app you're working on to support@apptentive.com and mention that you reached out on Github?

4) Is this preventing you from building the app or pushing a release to the app stores?

Let us know. Thanks!

**Comment by CaseyApptentive** [comment]
@Grasshooper following up. Let me know if you're still having any trouble.
