### ISSUE TITLE
New in app rate dialog is not being displayed

### ISSUE THREAD

**Issue by gmbett** [apptentive/apptentive-android#217]
Hello,

In our company we are trying to use the latest version of your SDK (version 5.6.0) which in theory brings support for Google Play In-App Review but I'm seeing an error in Logcat when the new rate dialog should be displayed:

```
2020-11-12 09:54:41.933 31780-31780/com.swisscom.mycloud E/Apptentive: [IN_APP_REVIEW] Unable to create in-app review manager
    java.lang.ClassCastException: com.swisscom.ngti.mycloud.MyCloudApplication cannot be cast to android.app.Activity
        at com.apptentive.android.sdk.external.DefaultInAppReviewManagerFactory.createReviewManager(DefaultInAppReviewManagerFactory.java:36)
        at com.apptentive.android.sdk.module.engagement.InAppRatingDialogInteractionLauncher.launch(InAppRatingDialogInteractionLauncher.java:46)
        at com.apptentive.android.sdk.module.engagement.InAppRatingDialogInteractionLauncher.launch(InAppRatingDialogInteractionLauncher.java:21)
        at com.apptentive.android.sdk.module.engagement.EngagementModule.launchInteraction(EngagementModule.java:135)
        at com.apptentive.android.sdk.module.engagement.EngagementModule$1.execute(EngagementModule.java:122)
        at com.apptentive.android.sdk.util.threading.DispatchTask.run(DispatchTask.java:39)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

It seems that you are trying to cast the context provided to the SDK (when is initialized) to Activity?

**Comment by CaseyApptentive** [comment]
Hi @gmbett, 

Great question. You are understanding this correctly. Apptentive controls who can see the Google Play Rating Dialog, where it is displayed, and how often we try to show it -- but Google's API requires that the Where Event used to launch it have an Activity Context. 

Here's a bit more depth in our docs: https://learn.apptentive.com/knowledge-base/requesting-ratings-on-google-play/#apptentive-rating-dialog-shown-instead-of-google-play-rating-dialog

Other Apptentive Interactions types -- which are fully 'owned' by Apptentive -- do not have the same restriction. Essentially, this is a rule handed down from Google directly. 

To fix this, you'll need to adjust how the Where Event is called in your code to ensure it has an Activity Context. It may also be wise to see if any of your other Events may not have an Activity Context either. Remember, other Apptentive Interactions do not strictly _require_ an Activity Context -- but if anyone adjusts the targeting of the Rating Dialog in the future, they do need to use an Event that works.

**Comment by gmbett** [comment]
Hi @CaseyApptentive, thanks for the explanation! 

I will adjust our implementation.
Cheers,
Germán

**Comment by CaseyApptentive** [comment]
Thanks for doing that. The new Google Play Rating Dialog works very well. I know it can take some legwork to make adjustments for it, but doing so is great.

**Comment by gmbett** [comment]
@CaseyApptentive I updated our implementation but still the rate dialog is not showing up, now I can see in the logs the following error:

```
I/Apptentive: [Apptentive Queue] [INTERACTIONS] Criteria evaluated => true
I/Apptentive: [INTERACTIONS] Launching interaction: 'InAppRatingDialog'
I/Apptentive: [Apptentive Queue] [INTERACTIONS] Engage event: 'com.apptentive#InAppRatingDialog#request'
D/ApptentiveUiManager: activityCreated: activity = com.google.android.play.core.common.PlayCoreDialogWrapperActivity@d06fe31, savedInstanceState = null
D/ApptentiveUiManager: activityStartedOrStopped: activity = com.google.android.play.core.common.PlayCoreDialogWrapperActivity@d06fe31, started = true
D/ApptentiveUiManager: Last activity set to com.google.android.play.core.common.PlayCoreDialogWrapperActivity@d06fe31
D/ApptentiveUiManager: Updated number of started activities: 2
E/Apptentive: [IN_APP_REVIEW] In-app review flow completed too fast (263 ms) and we have good reasons to believe it just failed silently.
I/Apptentive: [Apptentive Queue] [INTERACTIONS] Engage event: 'com.apptentive#InAppRatingDialog#not_shown'
D/ApptentiveUiManager: activityStartedOrStopped: activity = com.google.android.play.core.common.PlayCoreDialogWrapperActivity@d06fe31, started = false
D/ApptentiveUiManager: Last activity cleared, was com.google.android.play.core.common.PlayCoreDialogWrapperActivity@d06fe31
D/ApptentiveUiManager: Updated number of started activities: 1

**Comment by CaseyApptentive** [comment]
Great question @gmbett. 

So, you've hit a (really fun) expected behavior. Unfortunately, Google Play has given us a very helpful new tool with this Dialog, but there are several hoops to jump through to use it -- hoops that especially impact testing. Thanks for the logs. This is the key section:

```
E/Apptentive: [IN_APP_REVIEW] In-app review flow completed too fast (263 ms) and we have good reasons to believe it just failed silently.
I/Apptentive: [Apptentive Queue] [INTERACTIONS] Engage event: 'com.apptentive#InAppRatingDialog#not_shown'
```

This error means that Apptentive attempted to display the Google Play Rating Dialog, but that for at least one of a handful of expected reasons, the Dialog could not be shown. Here are a few of the most common reasons: 

- You must be testing on a version of the app downloaded from the Google Play Store. If testing in a simulator or something similar, the dialog cannot be presented.
- The account that’s attempting to see the dialog has hit its quota. This limit is imposed by Google directly, though they do not say exactly what that limit is.
- The customer already has a review within a test track.

Please check out the full list of reasons here: https://learn.apptentive.com/knowledge-base/requesting-ratings-on-google-play/#google-play-rating-dialog-not-shown

Every testing setup is a bit different, so let me know if any of those reasons are the likely culprit blocking the Rating Dialog from being shown.

For customers in the wild, we do _not_ expect to see these limitations very regularly, but it is possible. If it does come up, the Rating Dialog would fail silently -- so it's not a terrible customer experience. And, if you want to monitor how many customers we attempt to present the Dialog to but do not actually see it, you can see it on the front page of your Apptentive Dashboard -- that way you can be aware and make any targeting adjustments that might help reduce that number.

**Comment by gmbett** [comment]
Hi @CaseyApptentive  thanks again for your detailed response.

**Comment by CaseyApptentive** [comment]
No problem. Let us know if you need anything else.
